# Generated by Django 5.0.4 on 2024-04-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postaus',
            options={'verbose_name': 'postaus', 'verbose_name_plural': 'postaukset'},
        ),
    ]
