# Generated by Django 5.0.4 on 2024-04-08 14:28

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogi', '0002_alter_postaus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaus',
            name='teksti',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
